### ISSUE TITLE
 About Dataset

### ISSUE THREAD

**Issue by GreatWizard9519** [FelixOpolka/STGCN-PyTorch#2]
Hi,

Thanks for your work,
BTW, could I use the dataset from https://github.com/Davidham3/STGCN on your work?

**Comment by FelixOpolka** [comment]
Hey,
Having looked at the data set format briefly, it should be easy to use it with this model. You might have to convert it slightly before.

**Comment by GreatWizard9519** [comment]
> Hey,
> Having looked at the data set format briefly, it should be easy to use it with this model. You might have to convert it slightly before.

Thankss!
