### ISSUE TITLE
Why is the adjacent matrix not symmetric?

### ISSUE THREAD

**Issue by v6l4188** [FelixOpolka/STGCN-PyTorch#8]
Hi author,
    Thank you for your STGCN of PyTorch version. I found that the matrix in adj_mat.npy is not symmetric, but the matrix should be Wij=exp(-dij^2/sigma^2) (if Wij≠0). So why is that not symmetric?
Best wishes

**Comment by YuzhouLin** [comment]
Why does it need to be symmetric? 
The symmetric matrix means the connection is undirected. 

A non-symmetric matrix stands for the directed connection.

**Comment by michealowen** [comment]
I think the adjacency matrix has to be symmetric. In the STGCN paper , the author takes the sensor station in the crossing as a vertice, so the graph is not directed.
